export const agents = [
  {
    id: "angie-rincon",
    name: "Angee Rincon",
    clients: [
      {
        id: "yesith-ojeda",
        clientName: "Yesith Ojeda",
        company: "The Joker Truck LLC",
        stage: "Qualification Stage",
        cardStatus: "Pending",
        firstSwipe: "No",
        gallonLimit: "-",
        billingStatus: "Review",
        riskFlag: "Low",
        phone: "17736295409",
        email: "thejokertruck.llc@gmail.com",
        notes: "Cliente nuevo. Esperando validacion documental.",
      },
      {
        id: "juan-robles",
        clientName: "Juan Robles",
        company: "J&E Transportation",
        stage: "Qualification Stage",
        cardStatus: "Pending",
        firstSwipe: "No",
        gallonLimit: "-",
        billingStatus: "Review",
        riskFlag: "Low",
        phone: "19563254481",
        email: "jjrobles83@gmail.com",
        notes: "En espera de confirmacion de datos bancarios.",
      },
    ],
  },
  {
    id: "julian-sandoval",
    name: "Julian Sandoval",
    clients: [
      {
        id: "eugefria",
        clientName: "Jesus Garfias",
        company: "Angee Rincon",
        stage: "Qualification Stage",
        cardStatus: "In Progress",
        firstSwipe: "No",
        gallonLimit: "-",
        billingStatus: "Review",
        riskFlag: "Low",
        phone: "18302995702",
        email: "jesusgarfias80@gmail.com",
        notes: "Agendar llamada de onboarding.",
      },
      {
        id: "dagena-truck",
        clientName: "Dagena Trucking",
        company: "Dagena Trucking LLC",
        stage: "Qualification Stage",
        cardStatus: "Pending",
        firstSwipe: "No",
        gallonLimit: "-",
        billingStatus: "Review",
        riskFlag: "Medium",
        phone: "16692937632",
        email: "dagenatrucking@gmail.com",
        notes: "Completar informacion de unidad principal.",
      },
    ],
  },
  {
    id: "john-labarca",
    name: "John Labarca",
    clients: [
      {
        id: "raymond-lloyd",
        clientName: "Raymond Lloyd",
        company: "Quebec INC",
        stage: "Qualification Stage",
        cardStatus: "Approved",
        firstSwipe: "Yes",
        gallonLimit: "1200",
        billingStatus: "Current",
        riskFlag: "Low",
        phone: "18195714664",
        email: "raymond.lloyd.74@gmail.com",
        notes: "Cliente activo con buen historial.",
      },
    ],
  },
  {
    id: "linda-sabbagh",
    name: "Linda Sabbagh",
    clients: [
      {
        id: "alberto-garcia",
        clientName: "Alberto Garcia",
        company: "Martinez Trucking LLC",
        stage: "Qualification Stage",
        cardStatus: "Pending",
        firstSwipe: "No",
        gallonLimit: "-",
        billingStatus: "Review",
        riskFlag: "Low",
        phone: "12087036021",
        email: "ag625092@gmail.com",
        notes: "Pendiente validacion de insurance.",
      },
      {
        id: "jose-luis-montoya",
        clientName: "Jose Luiz Montoya",
        company: "JE & A Trucking",
        stage: "Qualification Stage",
        cardStatus: "In Progress",
        firstSwipe: "No",
        gallonLimit: "-",
        billingStatus: "Review",
        riskFlag: "Medium",
        phone: "14322729519",
        email: "jeatrucking7@gmail.com",
        notes: "Solicitar estado de cuenta actualizado.",
      },
      {
        id: "ismael-villareal",
        clientName: "Ismael Villarreal",
        company: "Villareal Carries LLC",
        stage: "Qualification Stage",
        cardStatus: "Pending",
        firstSwipe: "No",
        gallonLimit: "-",
        billingStatus: "Review",
        riskFlag: "Low",
        phone: "14699706084",
        email: "ismael94.7@outlook.com",
        notes: "Validar direcciones fiscales antes de aprobacion.",
      },
    ],
  },
  {
    id: "fabio-castillo",
    name: "Fabio Castillo",
    clients: [],
  },
  {
    id: "kevin-ruiz",
    name: "Kevin Ruiz",
    clients: [],
  },
  {
    id: "alejandra-giraldo",
    name: "Alejandra Giraldo",
    clients: [],
  },
];
